// auto generated by go tool dist

package runtime

const defaultGoroot = `/home/lintel/PandoraBox-MT7620/build_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-1.0.x/golang-1.4.2`
const theVersion = `go1.4.2`
var buildVersion = theVersion
